config/routes.rb
Rails.application.routes.draw do
  get 'static/index'

  devise_for :users
  resources :users, :except => [:index, :destroy]
  resources :dishes
  root :to => 'static#index'
  get '/booking' => 'static#booking'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dish
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :category
  has_many :ratings
  has_many :bookings
  has_many :users, :through => :bookings
  # belongs_to :user
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # has_many :dishes
  has_many :bookings
  has_many :dishes, :through => :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :img, :price)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @cat = Category.all
  end

  def booking
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :name, :picture, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dishes/_form.html.erb
<%= form_for(dish) do |f| %>
  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :img %>
    <%= f.text_field :img %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<div class="container">
    <div class="row">
        <!-- start -->
      <% @dishes.each do |dish| %>
        <div class="column is-one-third">
            <div class="something">
                <div id="oneA">
                    <div class="dishes-price">
                        <span id="price">$<%= dish.price %></span>
                    </div>
                    <div class="dishes-image">
                        <img src="<%= dish.img %>" style="width:100%;height:100%;">
                    </div>
                    <div class="dishes-name">
                        <span id="name" style="font-size: 1.2em;"><%= dish.name %></span>
                    </div>
                    <hr>
                    <div class="dishes-user-info">
                        <span><i>by</i></span>
                        <% if dish.users[0] %>
                        <span id="username"><%= dish.users[0].name %></span>
                        <% end %>
                        <br />
                        <span style="font-size: 0.6em;">FROM </span><br>
                        <span id="precinct" style="font-size: 0.8em;"><strong><%=dish.users[0].address%></strong></span>
                    </div>
                    <div>
                        <a href="/dishes/<%= dish.id %>"><i class="fa fa-dot-circle-o fa-3x" aria-hidden="true"></i></a>
                    </div>
                    <div class="dishes-rating">
                        <span>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star-o" aria-hidden="true"></i>
                            <i class="fa fa-star-o" aria-hidden="true"></i>
                          </span>
                        <span id="rating">(5)</span>
                    </div>
                </div>
            </div>
        </div>
      <% end %>
    </div>
</div>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<div class="container">
   <div class="row">
     <div class="column is-full center-div"><img src="<%=@dish.img%>"></div>
   </div>
   <div class="row">
     <div class="column is-full center-div title">Dining with <%=@dish.users[0].name%> at <br><br><span class='small'><%=@dish.users[0].address%></span></div>
   </div>
   <div class="row">
     <div class="column is-full center-div title"><iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d1994.343928082651!2d103.85217077633514!3d1.3639540116493825!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2ssg!4v1466910810653" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe></div>
   </div>
   <div class="row">
     <div class="column is-full center-div">Review | <span class="price">$<%=@dish.price%> </span><span class="greypax">per person</span></div>
   </div>
   <div class="row">
     <div class="column is-one-third center-div"></div>
     <div class="column is-one-third center-div">
       <select class="browser-default">
         <option value="" disabled selected>Wednesday 7:00pm</option>
         <option value="1">Thursday 7:00pm</option>
         <option value="2">Friday 7:00pm</option>
         <option value="3">Monday 7:00pm</option>
       </select>
       <select class="browser-default">
         <option value="" disabled selected>1 Guest</option>
         <option value="1">2 Guests</option>
         <option value="2">3 Guests</option>
         <option value="3">4 Guests</option>
       </select>

       <a class="btn fonttop waves-effect waves-light" href='/booking' type="submit" name="action">Chope</a>
     </div>
     <div class="column is-one-third center-div"></div>
   </div>
   <hr class="divide"></hr>
   <div class="row">
     <div class="column is-full center-div menu">Description</div>
   </div>
   <div class="row">
     <div class="column is-text-side"></div>
     <div class="column is-text center-div">
       <p class="menu-text">
         I am going to share my mee goreng with my neighbours, some say it is the best mee goreng in the whole of Singapore and maybe Malaysia.
       </p>
     </div>
     <div class="column is-text-side"></div>
   </div>
   <div class="row">
     <div class="column is-text-side"></div>
     <div class="column is-text center-div">
       <p class="menu-text">
         This meal includes unlimited servings of mee goreng, eat until you explode!
       </p>
     </div>
     <div class="column is-text-side"></div>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hdb</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar-container">
      <div class="navbar">
        <a class="navbar-links" id="navbar-logo" href="/"><i class="fa fa-male logo-people" aria-hidden="true"></i>
        <i class="fa fa-building-o" id="logo-building" aria-hidden="true"></i><i class="fa fa-female logo-people" aria-hidden="true"></i>
        <span id="brand-name">HungryGoWhichBlock</span></a>
        <a class="navbar-links navbar-navi" href="#"><span class="navbar-link">Feed Me Leh</span></a>
        <a class="navbar-links" id="invite" href="#"><span class="navbar-link">Invite</span></a>
        <a class="navbar-links navbar-login" href="/users/sign_in">Login</a>
        <a class="navbar-links" id="sit-down" href="/users/sign_up">Register</a>
      </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.text_field :picture %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Name</th>
      <th>Picture</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.name %></td>
        <td><%= user.picture %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @user.picture %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>